
### server port
server:
  port: 8081

#Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8180
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
#keycloak.security-constraints[0].authRoles[0]=user
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/customers/*
  principal-attribute: preferred_username